### PR TITLE
Restructes the package files

### PR DESCRIPTION
**Pull request by mdaffin**
This commit is meant to tidy up the package structure and build process a bit.
- Moves all the qml files to the contents/ui subdirectory. This is more
  in-line with the plasma package structure.
- CMakeLists files have been added to the appropriate subdirectories and
  called when appropriate. This makes it easier to maintain the different
  sub-folders.
- Sets Activities2.qml as the mainscript in the desktop file
- Makes use of the cmake configure_file to configure static files before build (this makes it easier to place version info in files as you only have to define it in once place)

This touches allot of files, though it is mostly just moving them around. You might want to pull it into a new branch and test it out before merging in case I forgot something.

This commit is to move your package structure closer to what homerun uses (which uses the standard plasma package layout) to make the port easier, I have included it in a separate branch as I think it should be used regardless of if you decides to uptake the port later and to make it easier to develop from a common base as this moves around so many files it would be a pain to merge in later.

Tell me if anything needs reworking or you don't agree with some of my changes.

### CODE REVIEW

**Comment by psifidotos** [comment]
james does this commit work for you? I use
plasmoidviewer workflow
but the plasmoid can not be found. (the workflow package could not be found)

**Comment by psifidotos** [comment]
also can you please add in the CMakeLists

```
    PATTERN ".directory" EXCLUDE
    PATTERN ".fuse*" EXCLUDE
```

in order not to install theses files?

**Comment by psifidotos** [comment]
james if I remove from the desktop file the lines:

X-Plasma-API=declarativeappletscript
X-Plasma-MainScript=ui/Activities2.qml

then things start to operate again....

are these two so important?

**Comment by psifidotos** [comment]
I am definitely positive for the restructuring if the problems are resolved.
I had tried it in the past also but my problem was that for hybrid plasmoids (tha use C++ and QML)
I had not found any references. If you say that this is the way to go as a standard I am definitely
possitive. About the .desktop file I dont know if there is a way to describe a hybrid plasmoid.

**Comment by mdaffin** [comment]
It was working for me when I tested it... Though I could have missed something.

Removing those two lines should not have worked since I changed the way the plasmoid creates the declarative context... if you remove them my other changes should have stopped the widget from finding the qml files and make it load a blank widget...

I suspect there are left over files from a previous install on you system, did you install to /usr? If so I think that is why, I installed to an isolated clean directory and setup the appropriate environment variables to launch it (and uninitialised my system version of workflow just to make sure (read: I tested it in a clean environment)). Will try it again on my laptop to make sure.

Also what do  the .fuse\* files belong to?

**Comment by mdaffin** [comment]
Hmm, works on my desktop but not on my laptop... and no obvious differences... will try to find and fix it...

**Comment by mdaffin** [comment]
Ok, I think I found where I messed up, should have a fix shortly. 

Edit: actually no, its not what I thought :S

**Comment by mdaffin** [comment]
Ok, I think I have solve it ;)

**Comment by mdaffin** [comment]
Also, when you want to merge, it is better to do a `git fetch` and then a `git rebase` as this create a cleaner more linear history (and less "merge commits").

If it fails just do `git rebase --abort` and then `git merge` to do a full merge (fyi git pull just does `git fetch && git merge`).

Though it is up to you, this is just how I normally do it.

**Comment by mdaffin** [comment]
I have added the exclude patterns back as well, but changed them to .\* and *~ which should catch more files you don't want.

**Comment by psifidotos** [comment]
james I tested it it's ok,
but about the rebase thing I need some help for future merges.

I will tell you what I did and please guide me in the correct command sequence

Your remote branch in my system is james147
The github remote branch is callsed github in my system

---

I created a new local branch called loc-jamesbuild
then:

git pull --rebase james147 package-restructure
I tested your commits then:
git checkout master (local master)
git merge loc-jamesbuild
git push james147 master:master

I wait for your feedback for future commits
(this project is my first attempt in KDE programming and git also so please be patient with me... :) )

**Comment by mdaffin** [comment]
> this project is my first attempt in KDE programming and git also so please be patient with me... :)

Thats fine :) we where all new once.

To be honest I did not know about the pull --rebase option, thanks for that.

But since you have already done a rebase and it has applied cleanly you should beable to just replace the `git merge` line with a `git rebase` to rebase my changes ontop of your work. If this does fail you can do `git rebase --abort` to cancel it then do a normal merge.

So using your example

```
git pull --rebase james147 package-restructure
# Test the commits
git checkout master # local master
git rebase loc-jamesbuild
# If and only if it fails do:
# git rebase --abort # Cancel the rebase and revert to befoew
# git merge loc-jamesbuild # Continue with a normal merge
git push james147 master:master
```

Tip: I make use of bash comments to make the code more copy and paste friendly ;) and easier to read.

I highly recommend reading the [gitpro](http://git-scm.com/book) book if you want to make the most of git (its free online). [This](http://git-scm.com/book/en/Git-Branching-Rebasing) chapter of it talks about rebasing and what it does to the history compared to merging.

Again, rebasing or merging it mostly a personal choice, but I tend to use it as it creates a cleaner more linear git history.

**Comment by mdaffin** [comment]
Actually, with the pull --rebase you may only need to do a `git merge` to fast-forward the changes.

**Pull request merged**
